// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protocols

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Msg                  map[string]string `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tag                  string            `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Id                   int64             `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsg() map[string]string {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Message) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "protocols.Message")
	proto.RegisterMapType((map[string]string)(nil), "protocols.Message.MsgEntry")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0xc9, 0xf9, 0x39,
	0xc5, 0x4a, 0x93, 0x18, 0xb9, 0xd8, 0x7d, 0x21, 0x92, 0x42, 0xba, 0x5c, 0xcc, 0xb9, 0xc5, 0xe9,
	0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xd2, 0x7a, 0x70, 0x45, 0x7a, 0x50, 0x05, 0x7a, 0xbe,
	0xc5, 0xe9, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41, 0x20, 0x75, 0x42, 0x02, 0x5c, 0xcc, 0x25, 0x89,
	0xe9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a,
	0x04, 0xb3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x53, 0x66, 0x8a, 0x94, 0x19, 0x17, 0x07, 0x4c, 0x0b,
	0x48, 0x75, 0x76, 0x6a, 0xa5, 0x04, 0x23, 0x44, 0x75, 0x76, 0x6a, 0xa5, 0x90, 0x08, 0x17, 0x6b,
	0x59, 0x62, 0x4e, 0x69, 0x2a, 0xd4, 0x04, 0x08, 0xc7, 0x8a, 0xc9, 0x82, 0x31, 0x89, 0x0d, 0x6c,
	0xb5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x08, 0x8a, 0x68, 0x88, 0xb7, 0x00, 0x00, 0x00,
}
